version: "3.8"

services:
  nginx:
    image: nginx:1.21.3-alpine
    container_name: budget-assistant.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/ssl/private:ro   
    networks:
      - budget-assistant
         
networks:
  budget-assistant:
    external: true
    
