version: "3.8"

services:
  budget-assistant-api.prod:
    image: lednev/budget-assistant.api:production
    container_name: budget-assistant.api.prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    networks:
      - budget-assistant

  budget-assistant-ui.prod:
    image: lednev/budget-assistant.ui:production
    container_name: budget-assistant.ui.prod
    build: ./BudgetAssistantFrontend
    ports:
      - "80"
    networks:
      - budget-assistant

networks:
  budget-assistant:
    external: true
