version: "3.8"

services:
  budget-assistant-api:
    image: budget-assistant.api
    container_name: budget-assistant.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    build:
      context: ./BudgetAssistantBackend
      dockerfile: BudgetAssistant.API/Dockerfile

  nginx:
    image: nginx:1.21.3-alpine
    container_name: budget-assistant.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/ssl/private:ro      
    links:
      - budget-assistant-api

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
